### ISSUE TITLE
Change working directory

### ISSUE THREAD

**Issue by pitosalas** [gismo07/coros#3]
If I understand correctly, something about the various .bashrc is not exactly convenient:

When I connect using vnc my $HOME is /workspace which does not contain a .bashrc. Instead the .bashrc from /root was run. And then if I mapped a directory between my file system and the container, the default is that /my_ros_data in the container corresponds to /ros-persistent-data locally.

I would like my catkin_ws to be in the mapped directory so it survives a restart. I tried remapping export HOME=/my_ros_data and that led to trouble.

Maybe you can explain the intended structure?

**Comment by jHaselberger** [comment]
There is only one `.bashrc` and two things to consider regarding the working directory:

- After staring the web IDE (Visual Studio Code) you should open your desired folder. In this case `/my_ros_data`. Everything here will be persistent.
- It is possible to set the working directory automatically to `/my_ros_data`. But I deliberately did not do that. This is because users can define a different path in the compose file.

If you want to change the default path: https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-does-code-server-decide-what-workspace-or-folder-to-open

**Comment by pitosalas** [comment]
Thanks... FYI I am using your docker file as the basis for https://github.com/pitosalas/tb3-ros which is going to be set up for students with various pre-installed local files so that they can work on them. So you can see that we set up prrexaamples and gen5 (as well as some tb3 stuff) in my_ros_data and things are set up so that once they run the image for the first time they see a ready to go catkin_ws etc. I didn't realize or understand the difference in intention of /workspace and /my_ros_data in your case. Do you have any suggestions about my approach? Thanks!
